name: Site workflow

on:
  push:
    branches:
      - master
jobs:
  sendMessage:
    name: Send commit message
    runs-on: ubuntu-latest
    steps:
      - uses: colutius/Telegram-Msg@main
        with:
          token: ${{ secrets.TELEGRAM_TOKEN }}
          chatid: ${{ secrets.TELEGRAM_TO }}
          message: |
            ${{ github.repository }} 有新的内容提交。

            提交人: [${{ github.actor }}]

            提交信息: ${{ github.event.commits[0].message }}
          is_notify: true
          is_preview: true
  CI:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [18]
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ matrix.os }}-node-v${{ matrix.node }}-deps-${{ hashFiles(format('{0}{1}', github.workspace, '/pnpm.lock')) }}
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: pnpm install
      - name: Build site
        run: pnpm build
      - name: Deploy to Cloudflare Workers
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
      - name: Send build success message
        uses: colutius/Telegram-Msg@main
        with:
          token: ${{ secrets.TELEGRAM_TOKEN }}
          chatid: ${{ secrets.TELEGRAM_TO }}
          message: |
            基于 Commit ${{ github.event.commits[0].message }} 的 Ou's Intro 新更改已构建并部署完成。

            现在可访问 https://www.gxres.net 以查看最新更改。
          is_notify: true
          is_preview: true
