name: Deploy site

on:
  push:
    branches:
      - main
jobs:
  CI:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Cache node_modules
        uses: actions/cache@v4
        env:
          cache-name: project-node-modules
        with:
          path: node_modules
          key: ${{runner.os}}-${{env.cache-name}}-${{hashFiles('package.json')}}
      - name: Install dependencies
        run: pnpm install
      - name: Build Nuxt (SSG Mode)
        run: pnpm generate
      - name: Deploy to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        with:
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          apiToken: ${{ secrets.CF_API_TOKEN }}
          command: deploy