name: Site workflow
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches:
      - master
jobs:
  sendMessage:
    name: Send commit message
    runs-on: ubuntu-latest
    steps:
      - uses: colutius/Telegram-Msg@main
        with:
          token: ${{ secrets.TELEGRAM_TOKEN }}
          chatid: ${{ secrets.TELEGRAM_TO }}
          message: |
            ${{ github.repository }} 有新的内容提交。

            提交人: ${{ github.actor }}

            提交信息（其一）: ${{ github.event.commits[0].message }}
          button: true
          button_name: 查看提交详情
          button_url: https://github.com/${{ github.repository }}/commit/${{github.sha}}
          is_notify: true
          is_preview: true
  CI:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [20]
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ matrix.os }}-node-v${{ matrix.node }}-deps-${{ hashFiles(format('{0}{1}', github.workspace, '/pnpm.lock')) }}
      - name: Install Vercel CLI
        run: pnpm add -g vercel@latest
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: pnpm install
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: Send build success message
        uses: colutius/Telegram-Msg@main
        with:
          token: ${{ secrets.TELEGRAM_TOKEN }}
          chatid: ${{ secrets.TELEGRAM_TO }}
          message: |
            Ou's Intro 的新更改已构建并部署完成。

            关联的提交信息：${{ github.event.commits[0].message }}

            现在可访问 https://www.gxres.net 以查看最新更改。
          button: true
          button_name: 现在访问
          button_url: https://www.gxres.net
          is_notify: true
          is_preview: true
