name: Deploy
on:
  push:
    branches:
      - master
jobs:
  CI:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [ 18 ]
    steps:
      - uses: actions/checkout@v3
      - name: Publish to Vercel
        uses: amondnet/vercel-action@v20
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-args: '--prod' #Optional
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID_STATIC }}
      - name: Send notification to Telegram Group
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            Ou's Intro 的一个新更改已应用。
            Commited by ${{ github.actor }} with message: ${{ github.event.commits[0].message }}
            您现在可以访问 https://www.restent.win 以查看最新更改是否生效。