name: Site workflow
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches:
      - master
jobs:
  sendMessage:
    name: Send commit message
    runs-on: ubuntu-latest
    steps:
      - uses: colutius/Telegram-Msg@main
        with:
          token: ${{ secrets.TELEGRAM_TOKEN }}
          chatid: ${{ secrets.TELEGRAM_TO }}
          message: |
            ${{ github.repository }} 有新的内容提交。

            提交人: ${{ github.actor }}

            提交信息: 

            ${{ github.event.commits[0].message }}

            * 如果存在多个 commits 同时 push，GitHub Actions 只能读取其中一个 commit 信息。
          button: true
          button_name: 查看提交详情
          button_url: https://github.com/${{ github.repository }}/commit/${{github.sha}}
          is_notify: true
          is_preview: true
  CI:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [20]
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Install Vercel CLI
        run: bun install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: Send build success message
        uses: colutius/Telegram-Msg@main
        with:
          token: ${{ secrets.TELEGRAM_TOKEN }}
          chatid: ${{ secrets.TELEGRAM_TO }}
          message: |
            Ou's Intro 的新更改已构建并部署完成。

            现在可访问 https://www.gxres.net 以查看最新更改。
          button: true
          button_name: 现在访问
          button_url: https://www.gxres.net
          is_notify: true
          is_preview: true
